version: "3.7"

services:
  app:
    build: ./
    restart: unless-stopped
    env_file: ./.env
    container_name: kiness_client
    image: kiness_client
    ports:
      - "7841:80"
    environment:
      - VITE_BASE_URL=$VITE_BASE_URL
